// Code generated by re2c 2.0.3 on Mon Dec 21 21:52:33 2020, DO NOT EDIT.
//line "lexer.go_":1
package zoe

type tkstack struct {
	top  int
	prev *tkstack
}

func (t *tkstack) push() *tkstack {
	n := &tkstack{top: 0, prev: t}
	return n
}

func (t *tkstack) pop() *tkstack {
	return t.prev
}

type LexerError struct {
	Filename string
	Message  string
	Line     uint32
	Column   uint32
	Offset   uint32
}

func (l LexerError) Error() string {
	return l.Message
}

func (z *File) Lex() error {
	//line "lexer.go":33
const (
	yyctop = iota
	yyccomment
	yycstr
)
//line "lexer.go_":30

	data, length := z.data, uint32(len(z.data))
	var offset uint32 = 0
	var start uint32 = 0
	var line uint32 = 0
	var col uint32 = 0
	cond := yyctop
	comment := 0 // recursive comments
	doc_comment := false
	var brace_stack *tkstack

	var marker uint32

	var updateLines = func() {
		for i := start; i < offset; i++ {
			char := data[i]
			if char == '\n' {
				line++
				col = 0
			} else {
				col++
			}
		}
	}

	var err = func() error {
		offset--
		updateLines()
		return LexerError{Message: "invalid input '" + string(data[offset]) + "'", Line: line, Column: col, Offset: offset, Filename: z.Filename}
	}

	var addTokenBounds = func(kind TokenKind, offsetStart uint32, offsetEnd uint32) {
		n := Token{}
		// n.Value = string(value)
		n.Kind = kind
		n.Offset = start + offsetStart
		n.Length = offset - offsetEnd - (n.Offset)
		n.Line = line
		n.Column = col
		updateLines()

		start = offset

		z.Tokens = append(z.Tokens, n)

		// count lines and columns before adding
	}

	var addToken = func(kind TokenKind) {
		addTokenBounds(kind, 0, 0)
	}

	
//line "lexer.go":93
{
	var yych byte
	yyaccept := 0
	switch (cond) {
	case yyctop:
		goto yyc_top
	case yyccomment:
		goto yyc_comment
	case yycstr:
		goto yyc_str
	}
/* *********************************** */
yyc_top:
	yych = data[offset]
	switch (yych) {
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case ' ':
		goto yy4
	case '!':
		goto yy7
	case '"':
		goto yy9
	case '#':
		goto yy11
	case '$':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'b':
		fallthrough
	case 'd':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'u':
		fallthrough
	case 'x':
		fallthrough
	case 'z':
		goto yy13
	case '%':
		goto yy16
	case '&':
		goto yy18
	case '\'':
		goto yy20
	case '(':
		goto yy21
	case ')':
		goto yy23
	case '*':
		goto yy25
	case '+':
		goto yy27
	case ',':
		goto yy29
	case '-':
		goto yy31
	case '.':
		goto yy33
	case '/':
		goto yy35
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy37
	case ':':
		goto yy40
	case ';':
		goto yy42
	case '<':
		goto yy44
	case '=':
		goto yy46
	case '>':
		goto yy48
	case '?':
		goto yy50
	case '@':
		goto yy52
	case '[':
		goto yy54
	case '\\':
		goto yy56
	case ']':
		goto yy57
	case 'a':
		goto yy59
	case 'c':
		goto yy60
	case 'e':
		goto yy61
	case 'f':
		goto yy62
	case 'i':
		goto yy63
	case 'l':
		goto yy64
	case 'm':
		goto yy65
	case 'n':
		goto yy66
	case 'r':
		goto yy67
	case 's':
		goto yy68
	case 't':
		goto yy69
	case 'v':
		goto yy70
	case 'w':
		goto yy71
	case 'y':
		goto yy72
	case '{':
		goto yy73
	case '|':
		goto yy75
	case '}':
		goto yy77
	default:
		if (offset >= length - 1) {
			goto yyeof1_top
		}
		goto yy2
	}
yy2:
	offset += 1
yy3:
//line "lexer.go_":98
	{ return err() }
//line "lexer.go":308
yy4:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case ' ':
		goto yy4
	default:
		goto yy6
	}
yy6:
//line "lexer.go_":100
	{ addToken(TK_WHITESPACE); goto yyc_top }
//line "lexer.go":325
yy7:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy79
	default:
		goto yy8
	}
yy8:
//line "lexer.go_":164
	{ addToken(TK_EXCLAM); goto yyc_top }
//line "lexer.go":338
yy9:
	offset += 1
	cond = yycstr
//line "lexer.go_":202
	{ addToken(TK_QUOTE); goto yyc_str }
//line "lexer.go":344
yy11:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		if (offset >= length - 1) {
			goto yy12
		}
		goto yy81
	case '(':
		goto yy83
	case '?':
		goto yy85
	default:
		goto yy82
	}
yy12:
//line "lexer.go_":201
	{ addToken(TK_COMMENT); goto yyc_top }
//line "lexer.go":364
yy13:
	offset += 1
	yych = data[offset]
yy14:
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy15
	}
yy15:
//line "lexer.go_":138
	{ addToken(TK_ID); goto yyc_top }
//line "lexer.go":504
yy16:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy88
	default:
		goto yy17
	}
yy17:
//line "lexer.go_":186
	{ addToken(TK_MOD); goto yyc_top }
//line "lexer.go":517
yy18:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy90
	default:
		goto yy19
	}
yy19:
//line "lexer.go_":184
	{ addToken(TK_AMP); goto yyc_top }
//line "lexer.go":530
yy20:
	yyaccept = 0
	offset += 1
	marker = offset
	yych = data[offset]
	if (yych <= 0x00) {
		if (offset >= length - 1) {
			goto yy3
		}
		goto yy92
	}
	goto yy93
yy21:
	offset += 1
//line "lexer.go_":143
	{ addToken(TK_LPAREN); goto yyc_top }
//line "lexer.go":547
yy23:
	offset += 1
//line "lexer.go_":144
	{ addToken(TK_RPAREN); goto yyc_top }
//line "lexer.go":552
yy25:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy98
	default:
		goto yy26
	}
yy26:
//line "lexer.go_":182
	{ addToken(TK_STAR); goto yyc_top }
//line "lexer.go":565
yy27:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '+':
		goto yy100
	case '=':
		goto yy102
	default:
		goto yy28
	}
yy28:
//line "lexer.go_":176
	{ addToken(TK_PLUS); goto yyc_top }
//line "lexer.go":580
yy29:
	offset += 1
//line "lexer.go_":172
	{ addToken(TK_COMMA); goto yyc_top }
//line "lexer.go":585
yy31:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '-':
		goto yy104
	case '=':
		goto yy106
	case '>':
		goto yy108
	default:
		goto yy32
	}
yy32:
//line "lexer.go_":179
	{ addToken(TK_MIN); goto yyc_top }
//line "lexer.go":602
yy33:
	yyaccept = 1
	offset += 1
	marker = offset
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy110
	default:
		goto yy34
	}
yy34:
//line "lexer.go_":171
	{ addToken(TK_DOT); goto yyc_top }
//line "lexer.go":617
yy35:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy112
	default:
		goto yy36
	}
yy36:
//line "lexer.go_":168
	{ addToken(TK_DIV); goto yyc_top }
//line "lexer.go":630
yy37:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy37
	default:
		goto yy39
	}
yy39:
//line "lexer.go_":139
	{ addToken(TK_NUMBER); goto yyc_top }
//line "lexer.go":661
yy40:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case ':':
		goto yy114
	default:
		goto yy41
	}
yy41:
//line "lexer.go_":173
	{ addToken(TK_COLON); goto yyc_top }
//line "lexer.go":674
yy42:
	offset += 1
//line "lexer.go_":175
	{ addToken(TK_SEMICOLON); goto yyc_top }
//line "lexer.go":679
yy44:
	offset += 1
//line "lexer.go_":165
	{ addToken(TK_LT); goto yyc_top }
//line "lexer.go":684
yy46:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy116
	default:
		goto yy47
	}
yy47:
//line "lexer.go_":188
	{ addToken(TK_EQ); goto yyc_top }
//line "lexer.go":697
yy48:
	offset += 1
//line "lexer.go_":166
	{ addToken(TK_GT); goto yyc_top }
//line "lexer.go":702
yy50:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy118
	case '=':
		goto yy120
	default:
		goto yy51
	}
yy51:
//line "lexer.go_":194
	{ addToken(TK_QUESTION); goto yyc_top }
//line "lexer.go":717
yy52:
	offset += 1
//line "lexer.go_":193
	{ addToken(TK_AT); goto yyc_top }
//line "lexer.go":722
yy54:
	offset += 1
//line "lexer.go_":145
	{ addToken(TK_LBRACE); goto yyc_top }
//line "lexer.go":727
yy56:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x07:
		fallthrough
	case 0x08:
		fallthrough
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case '\v':
		fallthrough
	case '\r':
		fallthrough
	case ' ':
		goto yy3
	case '\\':
		goto yy124
	default:
		if (offset >= length - 1) {
			goto yy3
		}
		goto yy122
	}
yy57:
	offset += 1
//line "lexer.go_":146
	{ addToken(TK_RBRACE); goto yyc_top }
//line "lexer.go":758
yy59:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy125
	default:
		goto yy14
	}
yy60:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy127
	default:
		goto yy14
	}
yy61:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy128
	case 'n':
		goto yy129
	case 'x':
		goto yy130
	default:
		goto yy14
	}
yy62:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy131
	case 'n':
		goto yy132
	case 'o':
		goto yy134
	default:
		goto yy14
	}
yy63:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'f':
		goto yy135
	case 'm':
		goto yy137
	case 'n':
		goto yy138
	case 's':
		goto yy140
	default:
		goto yy14
	}
yy64:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy142
	default:
		goto yy14
	}
yy65:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy143
	default:
		goto yy14
	}
yy66:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy144
	case 'o':
		goto yy145
	default:
		goto yy14
	}
yy67:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy146
	default:
		goto yy14
	}
yy68:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy147
	case 'w':
		goto yy148
	default:
		goto yy14
	}
yy69:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy149
	case 'h':
		goto yy150
	case 'r':
		goto yy151
	case 'y':
		goto yy152
	default:
		goto yy14
	}
yy70:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy153
	case 'o':
		goto yy154
	default:
		goto yy14
	}
yy71:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'h':
		goto yy155
	default:
		goto yy14
	}
yy72:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy156
	default:
		goto yy14
	}
yy73:
	offset += 1
//line "lexer.go_":147
	{
				addToken(TK_LBRACKET)
				if brace_stack != nil {
					brace_stack.top++
				}
				goto yyc_top
			}
//line "lexer.go":949
yy75:
	offset += 1
//line "lexer.go_":167
	{ addToken(TK_PIPE); goto yyc_top }
//line "lexer.go":954
yy77:
	offset += 1
//line "lexer.go_":154
	{
				addToken(TK_RBRACKET)
				if brace_stack != nil {
					if brace_stack.top == 0 {
						brace_stack = brace_stack.pop()
						goto yyc_str
					}
				}
				goto yyc_top
			}
//line "lexer.go":968
yy79:
	offset += 1
//line "lexer.go_":192
	{ addToken(TK_NOTEQ); goto yyc_top }
//line "lexer.go":973
yy81:
	offset += 1
	yych = data[offset]
yy82:
	switch (yych) {
	case '\n':
		goto yy12
	default:
		if (offset >= length - 1) {
			goto yy12
		}
		goto yy81
	}
yy83:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy84
	case '?':
		goto yy157
	default:
		if (offset >= length - 1) {
			goto yy84
		}
		goto yy81
	}
yy84:
//line "lexer.go_":198
	{ doc_comment = false; comment++; goto yyc_comment }
//line "lexer.go":1004
yy85:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy87
	default:
		if (offset >= length - 1) {
			goto yy87
		}
		goto yy85
	}
yy87:
//line "lexer.go_":200
	{ addToken(TK_DOCCOMMENT); goto yyc_top }
//line "lexer.go":1020
yy88:
	offset += 1
//line "lexer.go_":187
	{ addToken(TK_MODEQ); goto yyc_top }
//line "lexer.go":1025
yy90:
	offset += 1
//line "lexer.go_":185
	{ addToken(TK_AMPEQ); goto yyc_top }
//line "lexer.go":1030
yy92:
	offset += 1
	yych = data[offset]
yy93:
	switch (yych) {
	case '\'':
		goto yy94
	case '\\':
		goto yy96
	default:
		if (offset >= length - 1) {
			goto yy111
		}
		goto yy92
	}
yy94:
	offset += 1
yy95:
//line "lexer.go_":203
	{ addTokenBounds(TK_RAWSTR, 1, 1); goto yyc_top }
//line "lexer.go":1051
yy96:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\'':
		goto yy159
	case '\\':
		goto yy96
	default:
		if (offset >= length - 1) {
			goto yy111
		}
		goto yy92
	}
yy98:
	offset += 1
//line "lexer.go_":183
	{ addToken(TK_STAREQ); goto yyc_top }
//line "lexer.go":1070
yy100:
	offset += 1
//line "lexer.go_":178
	{ addToken(TK_PLUSPLUS); goto yyc_top }
//line "lexer.go":1075
yy102:
	offset += 1
//line "lexer.go_":177
	{ addToken(TK_PLUSEQ); goto yyc_top }
//line "lexer.go":1080
yy104:
	offset += 1
//line "lexer.go_":181
	{ addToken(TK_MINMIN); goto yyc_top }
//line "lexer.go":1085
yy106:
	offset += 1
//line "lexer.go_":180
	{ addToken(TK_MINEQ); goto yyc_top }
//line "lexer.go":1090
yy108:
	offset += 1
//line "lexer.go_":191
	{ addToken(TK_ARROW); goto yyc_top }
//line "lexer.go":1095
yy110:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy160
	default:
		goto yy111
	}
yy111:
	offset = marker
	switch (yyaccept) {
	case 0:
		goto yy3
	case 1:
		goto yy34
	default:
		goto yy95
	}
yy112:
	offset += 1
//line "lexer.go_":169
	{ addToken(TK_DIVEQ); goto yyc_top }
//line "lexer.go":1119
yy114:
	offset += 1
//line "lexer.go_":174
	{ addToken(TK_COLCOL); goto yyc_top }
//line "lexer.go":1124
yy116:
	offset += 1
//line "lexer.go_":189
	{ addToken(TK_EQEQ); goto yyc_top }
//line "lexer.go":1129
yy118:
	offset += 1
//line "lexer.go_":195
	{ addToken(TK_QUESTIONDOT); goto yyc_top }
//line "lexer.go":1134
yy120:
	offset += 1
//line "lexer.go_":196
	{ addToken(TK_QUESTIONEQ); goto yyc_top }
//line "lexer.go":1139
yy122:
	offset += 1
yy123:
//line "lexer.go_":141
	{ addToken(TK_CHAR); goto yyc_top }
//line "lexer.go":1145
yy124:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'f':
		fallthrough
	case 'n':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'v':
		fallthrough
	case 'x':
		goto yy122
	default:
		goto yy123
	}
yy125:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy126
	}
yy126:
//line "lexer.go_":105
	{ addToken(KW_AS); goto yyc_top }
//line "lexer.go":1309
yy127:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'n':
		goto yy162
	default:
		goto yy14
	}
yy128:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy163
	default:
		goto yy14
	}
yy129:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'u':
		goto yy164
	default:
		goto yy14
	}
yy130:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy165
	default:
		goto yy14
	}
yy131:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy166
	default:
		goto yy14
	}
yy132:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy133
	}
yy133:
//line "lexer.go_":112
	{ addToken(KW_FN); goto yyc_top }
//line "lexer.go":1503
yy134:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy167
	default:
		goto yy14
	}
yy135:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy136
	}
yy136:
//line "lexer.go_":122
	{ addToken(KW_IF); goto yyc_top }
//line "lexer.go":1653
yy137:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy169
	default:
		goto yy14
	}
yy138:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy139
	}
yy139:
//line "lexer.go_":120
	{ addToken(KW_IN); goto yyc_top }
//line "lexer.go":1803
yy140:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	case 'o':
		goto yy170
	default:
		goto yy141
	}
yy141:
//line "lexer.go_":127
	{ addToken(KW_IS); goto yyc_top }
//line "lexer.go":1942
yy142:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'c':
		goto yy172
	default:
		goto yy14
	}
yy143:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy173
	default:
		goto yy14
	}
yy144:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'm':
		goto yy174
	default:
		goto yy14
	}
yy145:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'n':
		goto yy175
	default:
		goto yy14
	}
yy146:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy176
	default:
		goto yy14
	}
yy147:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy177
	default:
		goto yy14
	}
yy148:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy178
	default:
		goto yy14
	}
yy149:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'k':
		goto yy179
	default:
		goto yy14
	}
yy150:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy180
	default:
		goto yy14
	}
yy151:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy181
	case 'u':
		goto yy182
	default:
		goto yy14
	}
yy152:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy183
	default:
		goto yy14
	}
yy153:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy184
	default:
		goto yy14
	}
yy154:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy186
	default:
		goto yy14
	}
yy155:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy187
	default:
		goto yy14
	}
yy156:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy188
	default:
		goto yy14
	}
yy157:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy158
	default:
		if (offset >= length - 1) {
			goto yy158
		}
		goto yy81
	}
yy158:
//line "lexer.go_":199
	{ doc_comment = true; comment++; goto yyc_comment }
//line "lexer.go":2125
yy159:
	yyaccept = 2
	offset += 1
	marker = offset
	yych = data[offset]
	switch (yych) {
	case '\'':
		goto yy94
	case '\\':
		goto yy96
	default:
		if (offset >= length - 1) {
			goto yy95
		}
		goto yy92
	}
yy160:
	offset += 1
//line "lexer.go_":170
	{ addToken(TK_ELLIPSIS); goto yyc_top }
//line "lexer.go":2146
yy162:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy189
	default:
		goto yy14
	}
yy163:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy190
	default:
		goto yy14
	}
yy164:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'm':
		goto yy192
	default:
		goto yy14
	}
yy165:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy194
	default:
		goto yy14
	}
yy166:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy195
	default:
		goto yy14
	}
yy167:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy168
	}
yy168:
//line "lexer.go_":119
	{ addToken(KW_FOR); goto yyc_top }
//line "lexer.go":2340
yy169:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy196
	case 'o':
		goto yy197
	default:
		goto yy14
	}
yy170:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy171
	}
yy171:
//line "lexer.go_":131
	{ addToken(KW_ISO); goto yyc_top }
//line "lexer.go":2492
yy172:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy198
	default:
		goto yy14
	}
yy173:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'h':
		goto yy199
	default:
		goto yy14
	}
yy174:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy200
	default:
		goto yy14
	}
yy175:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy201
	default:
		goto yy14
	}
yy176:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'u':
		goto yy203
	default:
		goto yy14
	}
yy177:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'u':
		goto yy204
	default:
		goto yy14
	}
yy178:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy205
	default:
		goto yy14
	}
yy179:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy206
	default:
		goto yy14
	}
yy180:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy208
	default:
		goto yy14
	}
yy181:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy210
	default:
		goto yy14
	}
yy182:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy211
	default:
		goto yy14
	}
yy183:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy213
	default:
		goto yy14
	}
yy184:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy185
	}
yy185:
//line "lexer.go_":109
	{ addToken(KW_VAR); goto yyc_top }
//line "lexer.go":2763
yy186:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'd':
		goto yy215
	default:
		goto yy14
	}
yy187:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy217
	default:
		goto yy14
	}
yy188:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy218
	default:
		goto yy14
	}
yy189:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy219
	default:
		goto yy14
	}
yy190:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy191
	}
yy191:
//line "lexer.go_":123
	{ addToken(KW_ELSE); goto yyc_top }
//line "lexer.go":2946
yy192:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy193
	}
yy193:
//line "lexer.go_":114
	{ addToken(KW_ENUM); goto yyc_top }
//line "lexer.go":3085
yy194:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy221
	default:
		goto yy14
	}
yy195:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy222
	default:
		goto yy14
	}
yy196:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy224
	default:
		goto yy14
	}
yy197:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy225
	default:
		goto yy14
	}
yy198:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy226
	default:
		goto yy14
	}
yy199:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy228
	default:
		goto yy14
	}
yy200:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy229
	default:
		goto yy14
	}
yy201:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy202
	}
yy202:
//line "lexer.go_":130
	{ addToken(KW_NONE); goto yyc_top }
//line "lexer.go":3301
yy203:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy230
	default:
		goto yy14
	}
yy204:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'c':
		goto yy231
	default:
		goto yy14
	}
yy205:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'c':
		goto yy232
	default:
		goto yy14
	}
yy206:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy207
	}
yy207:
//line "lexer.go_":132
	{ addToken(KW_TAKE); goto yyc_top }
//line "lexer.go":3473
yy208:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy209
	}
yy209:
//line "lexer.go_":134
	{ addToken(KW_THIS); goto yyc_top }
//line "lexer.go":3612
yy210:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy233
	default:
		goto yy14
	}
yy211:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy212
	}
yy212:
//line "lexer.go_":135
	{ addToken(KW_TRUE); goto yyc_top }
//line "lexer.go":3762
yy213:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	case 'o':
		goto yy235
	default:
		goto yy214
	}
yy214:
//line "lexer.go_":111
	{ addToken(KW_TYPE); goto yyc_top }
//line "lexer.go":3901
yy215:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy216
	}
yy216:
//line "lexer.go_":133
	{ addToken(KW_VOID); goto yyc_top }
//line "lexer.go":4040
yy217:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy236
	default:
		goto yy14
	}
yy218:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'd':
		goto yy238
	default:
		goto yy14
	}
yy219:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy220
	}
yy220:
//line "lexer.go_":110
	{ addToken(KW_CONST); goto yyc_top }
//line "lexer.go":4201
yy221:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy240
	default:
		goto yy14
	}
yy222:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy223
	}
yy223:
//line "lexer.go_":136
	{ addToken(KW_FALSE); goto yyc_top }
//line "lexer.go":4351
yy224:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'm':
		goto yy242
	default:
		goto yy14
	}
yy225:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy243
	default:
		goto yy14
	}
yy226:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy227
	}
yy227:
//line "lexer.go_":107
	{ addToken(KW_LOCAL); goto yyc_top }
//line "lexer.go":4512
yy228:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'd':
		goto yy245
	default:
		goto yy14
	}
yy229:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy247
	default:
		goto yy14
	}
yy230:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'n':
		goto yy248
	default:
		goto yy14
	}
yy231:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy250
	default:
		goto yy14
	}
yy232:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'h':
		goto yy252
	default:
		goto yy14
	}
yy233:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy234
	}
yy234:
//line "lexer.go_":115
	{ addToken(KW_TRAIT); goto yyc_top }
//line "lexer.go":4706
yy235:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'f':
		goto yy254
	default:
		goto yy14
	}
yy236:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy237
	}
yy237:
//line "lexer.go_":121
	{ addToken(KW_WHILE); goto yyc_top }
//line "lexer.go":4856
yy238:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy239
	}
yy239:
//line "lexer.go_":129
	{ addToken(KW_YIELD); goto yyc_top }
//line "lexer.go":4995
yy240:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy241
	}
yy241:
//line "lexer.go_":104
	{ addToken(KW_EXPORT); goto yyc_top }
//line "lexer.go":5134
yy242:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy256
	default:
		goto yy14
	}
yy243:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy244
	}
yy244:
//line "lexer.go_":103
	{ addToken(KW_IMPORT); goto yyc_top }
//line "lexer.go":5284
yy245:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy246
	}
yy246:
//line "lexer.go_":113
	{ addToken(KW_METHOD); goto yyc_top }
//line "lexer.go":5423
yy247:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy257
	default:
		goto yy14
	}
yy248:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy249
	}
yy249:
//line "lexer.go_":128
	{ addToken(KW_RETURN); goto yyc_top }
//line "lexer.go":5573
yy250:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy251
	}
yy251:
//line "lexer.go_":117
	{ addToken(KW_STRUCT); goto yyc_top }
//line "lexer.go":5712
yy252:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy253
	}
yy253:
//line "lexer.go_":124
	{ addToken(KW_SWITCH); goto yyc_top }
//line "lexer.go":5851
yy254:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy255
	}
yy255:
//line "lexer.go_":126
	{ addToken(KW_TYPEOF); goto yyc_top }
//line "lexer.go":5990
yy256:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'n':
		goto yy258
	default:
		goto yy14
	}
yy257:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'c':
		goto yy259
	default:
		goto yy14
	}
yy258:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy260
	default:
		goto yy14
	}
yy259:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy262
	default:
		goto yy14
	}
yy260:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy261
	}
yy261:
//line "lexer.go_":116
	{ addToken(KW_IMPLEMENT); goto yyc_top }
//line "lexer.go":6173
yy262:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy263
	}
yy263:
//line "lexer.go_":102
	{ addToken(KW_NAMESPACE); goto yyc_top }
//line "lexer.go":6312
yyeof1_top:
//line "lexer.go_":97
	{ addToken(TK_EOF); return nil }
//line "lexer.go":6316
/* *********************************** */
yyc_comment:
	yych = data[offset]
	switch (yych) {
	case '#':
		goto yy269
	default:
		if (offset >= length - 1) {
			goto yyeof1_comment
		}
		goto yy266
	}
yy266:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '#':
		goto yy268
	default:
		if (offset >= length - 1) {
			goto yy268
		}
		goto yy266
	}
yy268:
	goto yyc_comment
yy269:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '(':
		goto yy271
	case ')':
		goto yy273
	default:
		goto yy270
	}
yy270:
	goto yyc_comment
yy271:
	offset += 1
//line "lexer.go_":207
	{ comment++; goto yyc_comment }
//line "lexer.go":6360
yy273:
	offset += 1
//line "lexer.go_":208
	{ comment--; if comment == 0 {
				if doc_comment {
					addToken(TK_DOCCOMMENT)
				} else {
					addToken(TK_COMMENT)
				}
				goto yyc_top
				} else { goto yyc_comment } }
//line "lexer.go":6372
yyeof1_comment:
//line "lexer.go_":216
	{ err() }
//line "lexer.go":6376
/* *********************************** */
yyc_str:
	yych = data[offset]
	switch (yych) {
	case '"':
		goto yy280
	case '\\':
		goto yy282
	case '{':
		goto yy284
	default:
		if (offset >= length - 1) {
			goto yyeof1_str
		}
		goto yy277
	}
yy277:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '"':
		fallthrough
	case '\\':
		fallthrough
	case '{':
		goto yy279
	default:
		if (offset >= length - 1) {
			goto yy279
		}
		goto yy277
	}
yy279:
//line "lexer.go_":225
	{ addToken(TK_RAWSTR); goto yyc_str }
//line "lexer.go":6412
yy280:
	offset += 1
//line "lexer.go_":219
	{ addToken(TK_QUOTE); goto yyc_top }
//line "lexer.go":6417
yy282:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy283
	default:
		if (offset >= length - 1) {
			goto yy283
		}
		goto yy286
	}
yy283:
//line "lexer.go_":227
	{ return err() }
//line "lexer.go":6433
yy284:
	offset += 1
	cond = yyctop
//line "lexer.go_":220
	{
				addToken(TK_LBRACKET)
				brace_stack = brace_stack.push()
				goto yyc_top
			}
//line "lexer.go":6443
yy286:
	offset += 1
//line "lexer.go_":218
	{ addToken(TK_CHAR); goto yyc_str }
//line "lexer.go":6448
yyeof1_str:
//line "lexer.go_":228
	{ return err() }
//line "lexer.go":6452
}
//line "lexer.go_":229


	return nil
}
const (
  TK_EOF TokenKind = iota
KW_AS
KW_CONST
KW_ELSE
KW_ENUM
KW_EXPORT
KW_FALSE
KW_FN
KW_FOR
KW_IF
KW_IMPLEMENT
KW_IMPORT
KW_IN
KW_IS
KW_ISO
KW_LOCAL
KW_METHOD
KW_NAMESPACE
KW_NONE
KW_RETURN
KW_STRUCT
KW_SWITCH
KW_TAKE
KW_THIS
KW_TRAIT
KW_TRUE
KW_TYPE
KW_TYPEOF
KW_VAR
KW_VOID
KW_WHILE
KW_YIELD
TK_AMP
TK_AMPEQ
TK_ARROW
TK_AT
TK_CHAR
TK_COLCOL
TK_COLON
TK_COMMA
TK_COMMENT
TK_DIV
TK_DIVEQ
TK_DOCCOMMENT
TK_DOT
TK_ELLIPSIS
TK_EQ
TK_EQEQ
TK_EXCLAM
TK_FATARROW
TK_GT
TK_ID
TK_LBRACE
TK_LBRACKET
TK_LPAREN
TK_LT
TK_MIN
TK_MINEQ
TK_MINMIN
TK_MOD
TK_MODEQ
TK_NOTEQ
TK_NUMBER
TK_PIPE
TK_PLUS
TK_PLUSEQ
TK_PLUSPLUS
TK_QUESTION
TK_QUESTIONDOT
TK_QUESTIONEQ
TK_QUOTE
TK_RAWSTR
TK_RBRACE
TK_RBRACKET
TK_RPAREN
TK_SEMICOLON
TK_STAR
TK_STAREQ
TK_WHITESPACE
TK__MAX
)
var tokstr = [...]string{
KW_AS: "KW_AS",
KW_CONST: "KW_CONST",
KW_ELSE: "KW_ELSE",
KW_ENUM: "KW_ENUM",
KW_EXPORT: "KW_EXPORT",
KW_FALSE: "KW_FALSE",
KW_FN: "KW_FN",
KW_FOR: "KW_FOR",
KW_IF: "KW_IF",
KW_IMPLEMENT: "KW_IMPLEMENT",
KW_IMPORT: "KW_IMPORT",
KW_IN: "KW_IN",
KW_IS: "KW_IS",
KW_ISO: "KW_ISO",
KW_LOCAL: "KW_LOCAL",
KW_METHOD: "KW_METHOD",
KW_NAMESPACE: "KW_NAMESPACE",
KW_NONE: "KW_NONE",
KW_RETURN: "KW_RETURN",
KW_STRUCT: "KW_STRUCT",
KW_SWITCH: "KW_SWITCH",
KW_TAKE: "KW_TAKE",
KW_THIS: "KW_THIS",
KW_TRAIT: "KW_TRAIT",
KW_TRUE: "KW_TRUE",
KW_TYPE: "KW_TYPE",
KW_TYPEOF: "KW_TYPEOF",
KW_VAR: "KW_VAR",
KW_VOID: "KW_VOID",
KW_WHILE: "KW_WHILE",
KW_YIELD: "KW_YIELD",
TK_AMP: "TK_AMP",
TK_AMPEQ: "TK_AMPEQ",
TK_ARROW: "TK_ARROW",
TK_AT: "TK_AT",
TK_CHAR: "TK_CHAR",
TK_COLCOL: "TK_COLCOL",
TK_COLON: "TK_COLON",
TK_COMMA: "TK_COMMA",
TK_COMMENT: "TK_COMMENT",
TK_DIV: "TK_DIV",
TK_DIVEQ: "TK_DIVEQ",
TK_DOCCOMMENT: "TK_DOCCOMMENT",
TK_DOT: "TK_DOT",
TK_ELLIPSIS: "TK_ELLIPSIS",
TK_EOF: "TK_EOF",
TK_EQ: "TK_EQ",
TK_EQEQ: "TK_EQEQ",
TK_EXCLAM: "TK_EXCLAM",
TK_FATARROW: "TK_FATARROW",
TK_GT: "TK_GT",
TK_ID: "TK_ID",
TK_LBRACE: "TK_LBRACE",
TK_LBRACKET: "TK_LBRACKET",
TK_LPAREN: "TK_LPAREN",
TK_LT: "TK_LT",
TK_MIN: "TK_MIN",
TK_MINEQ: "TK_MINEQ",
TK_MINMIN: "TK_MINMIN",
TK_MOD: "TK_MOD",
TK_MODEQ: "TK_MODEQ",
TK_NOTEQ: "TK_NOTEQ",
TK_NUMBER: "TK_NUMBER",
TK_PIPE: "TK_PIPE",
TK_PLUS: "TK_PLUS",
TK_PLUSEQ: "TK_PLUSEQ",
TK_PLUSPLUS: "TK_PLUSPLUS",
TK_QUESTION: "TK_QUESTION",
TK_QUESTIONDOT: "TK_QUESTIONDOT",
TK_QUESTIONEQ: "TK_QUESTIONEQ",
TK_QUOTE: "TK_QUOTE",
TK_RAWSTR: "TK_RAWSTR",
TK_RBRACE: "TK_RBRACE",
TK_RBRACKET: "TK_RBRACKET",
TK_RPAREN: "TK_RPAREN",
TK_SEMICOLON: "TK_SEMICOLON",
TK_STAR: "TK_STAR",
TK_STAREQ: "TK_STAREQ",
TK_WHITESPACE: "TK_WHITESPACE",
}
