// Code generated by re2c 2.0.3 on Tue Dec 15 23:40:19 2020, DO NOT EDIT.
//line "lexer.go_":1
package zoe

type tkstack struct {
	top  int
	prev *tkstack
}

func (t *tkstack) push() *tkstack {
	n := &tkstack{top: 0, prev: t}
	return n
}

func (t *tkstack) pop() *tkstack {
	return t.prev
}

type LexerError struct {
	Filename string
	Message  string
	Line     uint32
	Column   uint32
	Offset   uint32
}

func (l LexerError) Error() string {
	return l.Message
}

func (z *File) Lex() error {
	//line "lexer.go":33
const (
	yyctop = iota
	yyccomment
	yycstr
)
//line "lexer.go_":30

	data, length := z.data, uint32(len(z.data))
	var offset uint32 = 0
	var start uint32 = 0
	var line uint32 = 1
	var col uint32 = 1
	cond := yyctop
	comment := 0 // recursive comments
	doc_comment := false
	var brace_stack *tkstack

	var marker uint32

	var updateLines = func() {
		for i := start; i < offset; i++ {
			char := data[i]
			if char == '\n' {
				line++
				col = 1
			} else {
				col++
			}
		}
	}

	var err = func() error {
		offset--
		updateLines()
		return LexerError{Message: "invalid input '" + string(data[offset]) + "'", Line: line, Column: col, Offset: offset, Filename: z.Filename}
	}

	var addTokenBounds = func(kind TokenKind, offsetStart uint32, offsetEnd uint32) {
		n := Token{}
		// n.Value = string(value)
		n.Start = start + offsetStart
		n.End = offset - offsetEnd
		n.Kind = kind
		n.Line = line
		n.Column = col
		updateLines()
		n.LineEnd = line
		n.ColumnEnd = col

		start = offset

		is_meaningful := kind != TK_WHITESPACE && kind != TK_COMMENT
		if is_meaningful {
			z.Tokens = append(z.Tokens, n)
		}

		// count lines and columns before adding
	}

	var addToken = func(kind TokenKind) {
		addTokenBounds(kind, 0, 0)
	}

	
//line "lexer.go":98
{
	var yych byte
	yyaccept := 0
	switch (cond) {
	case yyctop:
		goto yyc_top
	case yyccomment:
		goto yyc_comment
	case yycstr:
		goto yyc_str
	}
/* *********************************** */
yyc_top:
	yych = data[offset]
	switch (yych) {
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case ' ':
		goto yy4
	case '!':
		goto yy7
	case '"':
		goto yy9
	case '#':
		goto yy11
	case '$':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'b':
		fallthrough
	case 'd':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'u':
		fallthrough
	case 'x':
		fallthrough
	case 'z':
		goto yy13
	case '%':
		goto yy16
	case '&':
		goto yy18
	case '\'':
		goto yy20
	case '(':
		goto yy21
	case ')':
		goto yy23
	case '*':
		goto yy25
	case '+':
		goto yy27
	case ',':
		goto yy29
	case '-':
		goto yy31
	case '.':
		goto yy33
	case '/':
		goto yy35
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy37
	case ':':
		goto yy40
	case ';':
		goto yy42
	case '<':
		goto yy44
	case '=':
		goto yy46
	case '>':
		goto yy48
	case '?':
		goto yy50
	case '@':
		goto yy52
	case '[':
		goto yy54
	case '\\':
		goto yy56
	case ']':
		goto yy57
	case 'a':
		goto yy59
	case 'c':
		goto yy60
	case 'e':
		goto yy61
	case 'f':
		goto yy62
	case 'i':
		goto yy63
	case 'l':
		goto yy64
	case 'm':
		goto yy65
	case 'n':
		goto yy66
	case 'r':
		goto yy67
	case 's':
		goto yy68
	case 't':
		goto yy69
	case 'v':
		goto yy70
	case 'w':
		goto yy71
	case 'y':
		goto yy72
	case '{':
		goto yy73
	case '|':
		goto yy75
	case '}':
		goto yy77
	default:
		if (offset >= length - 1) {
			goto yyeof1_top
		}
		goto yy2
	}
yy2:
	offset += 1
yy3:
//line "lexer.go_":103
	{ return err() }
//line "lexer.go":313
yy4:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case ' ':
		goto yy4
	default:
		goto yy6
	}
yy6:
//line "lexer.go_":105
	{ addToken(TK_WHITESPACE); goto yyc_top }
//line "lexer.go":330
yy7:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy79
	default:
		goto yy8
	}
yy8:
//line "lexer.go_":166
	{ addToken(TK_EXCLAM); goto yyc_top }
//line "lexer.go":343
yy9:
	offset += 1
	cond = yycstr
//line "lexer.go_":203
	{ addToken(TK_QUOTE); goto yyc_str }
//line "lexer.go":349
yy11:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		if (offset >= length - 1) {
			goto yy12
		}
		goto yy81
	case '(':
		goto yy83
	case '?':
		goto yy85
	default:
		goto yy82
	}
yy12:
//line "lexer.go_":202
	{ addToken(TK_COMMENT); goto yyc_top }
//line "lexer.go":369
yy13:
	offset += 1
	yych = data[offset]
yy14:
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy15
	}
yy15:
//line "lexer.go_":140
	{ addToken(TK_ID); goto yyc_top }
//line "lexer.go":509
yy16:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy88
	default:
		goto yy17
	}
yy17:
//line "lexer.go_":187
	{ addToken(TK_MOD); goto yyc_top }
//line "lexer.go":522
yy18:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy90
	default:
		goto yy19
	}
yy19:
//line "lexer.go_":185
	{ addToken(TK_AMP); goto yyc_top }
//line "lexer.go":535
yy20:
	yyaccept = 0
	offset += 1
	marker = offset
	yych = data[offset]
	if (yych <= 0x00) {
		if (offset >= length - 1) {
			goto yy3
		}
		goto yy92
	}
	goto yy93
yy21:
	offset += 1
//line "lexer.go_":145
	{ addToken(TK_LPAREN); goto yyc_top }
//line "lexer.go":552
yy23:
	offset += 1
//line "lexer.go_":146
	{ addToken(TK_RPAREN); goto yyc_top }
//line "lexer.go":557
yy25:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy98
	default:
		goto yy26
	}
yy26:
//line "lexer.go_":183
	{ addToken(TK_STAR); goto yyc_top }
//line "lexer.go":570
yy27:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '+':
		goto yy100
	case '=':
		goto yy102
	default:
		goto yy28
	}
yy28:
//line "lexer.go_":177
	{ addToken(TK_PLUS); goto yyc_top }
//line "lexer.go":585
yy29:
	offset += 1
//line "lexer.go_":174
	{ addToken(TK_COMMA); goto yyc_top }
//line "lexer.go":590
yy31:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '-':
		goto yy104
	case '=':
		goto yy106
	case '>':
		goto yy108
	default:
		goto yy32
	}
yy32:
//line "lexer.go_":180
	{ addToken(TK_MIN); goto yyc_top }
//line "lexer.go":607
yy33:
	yyaccept = 1
	offset += 1
	marker = offset
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy110
	default:
		goto yy34
	}
yy34:
//line "lexer.go_":173
	{ addToken(TK_DOT); goto yyc_top }
//line "lexer.go":622
yy35:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy112
	default:
		goto yy36
	}
yy36:
//line "lexer.go_":170
	{ addToken(TK_DIV); goto yyc_top }
//line "lexer.go":635
yy37:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy37
	default:
		goto yy39
	}
yy39:
//line "lexer.go_":141
	{ addToken(TK_NUMBER); goto yyc_top }
//line "lexer.go":666
yy40:
	offset += 1
//line "lexer.go_":175
	{ addToken(TK_COLON); goto yyc_top }
//line "lexer.go":671
yy42:
	offset += 1
//line "lexer.go_":176
	{ addToken(TK_SEMICOLON); goto yyc_top }
//line "lexer.go":676
yy44:
	offset += 1
//line "lexer.go_":167
	{ addToken(TK_LT); goto yyc_top }
//line "lexer.go":681
yy46:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy114
	default:
		goto yy47
	}
yy47:
//line "lexer.go_":189
	{ addToken(TK_EQ); goto yyc_top }
//line "lexer.go":694
yy48:
	offset += 1
//line "lexer.go_":168
	{ addToken(TK_GT); goto yyc_top }
//line "lexer.go":699
yy50:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy116
	case '=':
		goto yy118
	default:
		goto yy51
	}
yy51:
//line "lexer.go_":195
	{ addToken(TK_QUESTION); goto yyc_top }
//line "lexer.go":714
yy52:
	offset += 1
//line "lexer.go_":194
	{ addToken(TK_AT); goto yyc_top }
//line "lexer.go":719
yy54:
	offset += 1
//line "lexer.go_":147
	{ addToken(TK_LBRACE); goto yyc_top }
//line "lexer.go":724
yy56:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x07:
		fallthrough
	case 0x08:
		fallthrough
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case '\v':
		fallthrough
	case '\r':
		fallthrough
	case ' ':
		goto yy3
	case '\\':
		goto yy122
	default:
		if (offset >= length - 1) {
			goto yy3
		}
		goto yy120
	}
yy57:
	offset += 1
//line "lexer.go_":148
	{ addToken(TK_RBRACE); goto yyc_top }
//line "lexer.go":755
yy59:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy123
	default:
		goto yy14
	}
yy60:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy125
	default:
		goto yy14
	}
yy61:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy126
	case 'n':
		goto yy127
	case 'x':
		goto yy128
	default:
		goto yy14
	}
yy62:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy129
	case 'n':
		goto yy130
	case 'o':
		goto yy132
	default:
		goto yy14
	}
yy63:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'f':
		goto yy133
	case 'm':
		goto yy135
	case 'n':
		goto yy136
	case 's':
		goto yy138
	default:
		goto yy14
	}
yy64:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy140
	default:
		goto yy14
	}
yy65:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy141
	default:
		goto yy14
	}
yy66:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy142
	case 'o':
		goto yy143
	default:
		goto yy14
	}
yy67:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy144
	default:
		goto yy14
	}
yy68:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy145
	default:
		goto yy14
	}
yy69:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'h':
		goto yy146
	case 'r':
		goto yy147
	case 'y':
		goto yy148
	default:
		goto yy14
	}
yy70:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy149
	case 'o':
		goto yy150
	default:
		goto yy14
	}
yy71:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'h':
		goto yy151
	default:
		goto yy14
	}
yy72:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy152
	default:
		goto yy14
	}
yy73:
	offset += 1
//line "lexer.go_":149
	{
				addToken(TK_LBRACKET)
				if brace_stack != nil {
					brace_stack.top++
				}
				goto yyc_top
			}
//line "lexer.go":942
yy75:
	offset += 1
//line "lexer.go_":169
	{ addToken(TK_PIPE); goto yyc_top }
//line "lexer.go":947
yy77:
	offset += 1
//line "lexer.go_":156
	{
				addToken(TK_RBRACKET)
				if brace_stack != nil {
					if brace_stack.top == 0 {
						brace_stack = brace_stack.pop()
						goto yyc_str
					}
				}
				goto yyc_top
			}
//line "lexer.go":961
yy79:
	offset += 1
//line "lexer.go_":193
	{ addToken(TK_NOTEQ); goto yyc_top }
//line "lexer.go":966
yy81:
	offset += 1
	yych = data[offset]
yy82:
	switch (yych) {
	case '\n':
		goto yy12
	default:
		if (offset >= length - 1) {
			goto yy12
		}
		goto yy81
	}
yy83:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy84
	case '?':
		goto yy153
	default:
		if (offset >= length - 1) {
			goto yy84
		}
		goto yy81
	}
yy84:
//line "lexer.go_":199
	{ doc_comment = false; comment++; goto yyc_comment }
//line "lexer.go":997
yy85:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy87
	default:
		if (offset >= length - 1) {
			goto yy87
		}
		goto yy85
	}
yy87:
//line "lexer.go_":201
	{ addToken(TK_DOCCOMMENT); goto yyc_top }
//line "lexer.go":1013
yy88:
	offset += 1
//line "lexer.go_":188
	{ addToken(TK_MODEQ); goto yyc_top }
//line "lexer.go":1018
yy90:
	offset += 1
//line "lexer.go_":186
	{ addToken(TK_AMPEQ); goto yyc_top }
//line "lexer.go":1023
yy92:
	offset += 1
	yych = data[offset]
yy93:
	switch (yych) {
	case '\'':
		goto yy94
	case '\\':
		goto yy96
	default:
		if (offset >= length - 1) {
			goto yy111
		}
		goto yy92
	}
yy94:
	offset += 1
yy95:
//line "lexer.go_":204
	{ addTokenBounds(TK_RAWSTR, 1, 1); goto yyc_top }
//line "lexer.go":1044
yy96:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\'':
		goto yy155
	case '\\':
		goto yy96
	default:
		if (offset >= length - 1) {
			goto yy111
		}
		goto yy92
	}
yy98:
	offset += 1
//line "lexer.go_":184
	{ addToken(TK_STAREQ); goto yyc_top }
//line "lexer.go":1063
yy100:
	offset += 1
//line "lexer.go_":179
	{ addToken(TK_PLUSPLUS); goto yyc_top }
//line "lexer.go":1068
yy102:
	offset += 1
//line "lexer.go_":178
	{ addToken(TK_PLUSEQ); goto yyc_top }
//line "lexer.go":1073
yy104:
	offset += 1
//line "lexer.go_":182
	{ addToken(TK_MINMIN); goto yyc_top }
//line "lexer.go":1078
yy106:
	offset += 1
//line "lexer.go_":181
	{ addToken(TK_MINEQ); goto yyc_top }
//line "lexer.go":1083
yy108:
	offset += 1
//line "lexer.go_":192
	{ addToken(TK_ARROW); goto yyc_top }
//line "lexer.go":1088
yy110:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy156
	default:
		goto yy111
	}
yy111:
	offset = marker
	switch (yyaccept) {
	case 0:
		goto yy3
	case 1:
		goto yy34
	default:
		goto yy95
	}
yy112:
	offset += 1
//line "lexer.go_":171
	{ addToken(TK_DIVEQ); goto yyc_top }
//line "lexer.go":1112
yy114:
	offset += 1
//line "lexer.go_":190
	{ addToken(TK_EQEQ); goto yyc_top }
//line "lexer.go":1117
yy116:
	offset += 1
//line "lexer.go_":196
	{ addToken(TK_QUESTIONDOT); goto yyc_top }
//line "lexer.go":1122
yy118:
	offset += 1
//line "lexer.go_":197
	{ addToken(TK_QUESTIONEQ); goto yyc_top }
//line "lexer.go":1127
yy120:
	offset += 1
yy121:
//line "lexer.go_":143
	{ addToken(TK_CHAR); goto yyc_top }
//line "lexer.go":1133
yy122:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'f':
		fallthrough
	case 'n':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'v':
		fallthrough
	case 'x':
		goto yy120
	default:
		goto yy121
	}
yy123:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy124
	}
yy124:
//line "lexer.go_":110
	{ addToken(KW_AS); goto yyc_top }
//line "lexer.go":1297
yy125:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'n':
		goto yy158
	default:
		goto yy14
	}
yy126:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy159
	default:
		goto yy14
	}
yy127:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'u':
		goto yy160
	default:
		goto yy14
	}
yy128:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy161
	default:
		goto yy14
	}
yy129:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy162
	default:
		goto yy14
	}
yy130:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy131
	}
yy131:
//line "lexer.go_":117
	{ addToken(KW_FN); goto yyc_top }
//line "lexer.go":1491
yy132:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy163
	default:
		goto yy14
	}
yy133:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy134
	}
yy134:
//line "lexer.go_":126
	{ addToken(KW_IF); goto yyc_top }
//line "lexer.go":1641
yy135:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy165
	default:
		goto yy14
	}
yy136:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy137
	}
yy137:
//line "lexer.go_":124
	{ addToken(KW_IN); goto yyc_top }
//line "lexer.go":1791
yy138:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	case 'o':
		goto yy166
	default:
		goto yy139
	}
yy139:
//line "lexer.go_":130
	{ addToken(KW_IS); goto yyc_top }
//line "lexer.go":1930
yy140:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'c':
		goto yy168
	default:
		goto yy14
	}
yy141:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy169
	default:
		goto yy14
	}
yy142:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'm':
		goto yy170
	default:
		goto yy14
	}
yy143:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'n':
		goto yy171
	default:
		goto yy14
	}
yy144:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy172
	default:
		goto yy14
	}
yy145:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy173
	default:
		goto yy14
	}
yy146:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy174
	default:
		goto yy14
	}
yy147:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy175
	case 'u':
		goto yy176
	default:
		goto yy14
	}
yy148:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy177
	default:
		goto yy14
	}
yy149:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy178
	default:
		goto yy14
	}
yy150:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy180
	default:
		goto yy14
	}
yy151:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy181
	default:
		goto yy14
	}
yy152:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy182
	default:
		goto yy14
	}
yy153:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy154
	default:
		if (offset >= length - 1) {
			goto yy154
		}
		goto yy81
	}
yy154:
//line "lexer.go_":200
	{ doc_comment = true; comment++; goto yyc_comment }
//line "lexer.go":2091
yy155:
	yyaccept = 2
	offset += 1
	marker = offset
	yych = data[offset]
	switch (yych) {
	case '\'':
		goto yy94
	case '\\':
		goto yy96
	default:
		if (offset >= length - 1) {
			goto yy95
		}
		goto yy92
	}
yy156:
	offset += 1
//line "lexer.go_":172
	{ addToken(TK_ELLIPSIS); goto yyc_top }
//line "lexer.go":2112
yy158:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy183
	default:
		goto yy14
	}
yy159:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy184
	default:
		goto yy14
	}
yy160:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'm':
		goto yy186
	default:
		goto yy14
	}
yy161:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy188
	default:
		goto yy14
	}
yy162:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy189
	default:
		goto yy14
	}
yy163:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy164
	}
yy164:
//line "lexer.go_":123
	{ addToken(KW_FOR); goto yyc_top }
//line "lexer.go":2306
yy165:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy190
	default:
		goto yy14
	}
yy166:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy167
	}
yy167:
//line "lexer.go_":134
	{ addToken(KW_ISO); goto yyc_top }
//line "lexer.go":2456
yy168:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy191
	default:
		goto yy14
	}
yy169:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'h':
		goto yy192
	default:
		goto yy14
	}
yy170:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy193
	default:
		goto yy14
	}
yy171:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy194
	default:
		goto yy14
	}
yy172:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'u':
		goto yy196
	default:
		goto yy14
	}
yy173:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'u':
		goto yy197
	default:
		goto yy14
	}
yy174:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy198
	default:
		goto yy14
	}
yy175:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'i':
		goto yy200
	default:
		goto yy14
	}
yy176:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy201
	default:
		goto yy14
	}
yy177:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy203
	default:
		goto yy14
	}
yy178:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy179
	}
yy179:
//line "lexer.go_":114
	{ addToken(KW_VAR); goto yyc_top }
//line "lexer.go":2705
yy180:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'd':
		goto yy205
	default:
		goto yy14
	}
yy181:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy207
	default:
		goto yy14
	}
yy182:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy208
	default:
		goto yy14
	}
yy183:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy209
	default:
		goto yy14
	}
yy184:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy185
	}
yy185:
//line "lexer.go_":127
	{ addToken(KW_ELSE); goto yyc_top }
//line "lexer.go":2888
yy186:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy187
	}
yy187:
//line "lexer.go_":119
	{ addToken(KW_ENUM); goto yyc_top }
//line "lexer.go":3027
yy188:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy211
	default:
		goto yy14
	}
yy189:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy212
	default:
		goto yy14
	}
yy190:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy214
	default:
		goto yy14
	}
yy191:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'l':
		goto yy215
	default:
		goto yy14
	}
yy192:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'o':
		goto yy217
	default:
		goto yy14
	}
yy193:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 's':
		goto yy218
	default:
		goto yy14
	}
yy194:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy195
	}
yy195:
//line "lexer.go_":133
	{ addToken(KW_NONE); goto yyc_top }
//line "lexer.go":3232
yy196:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'r':
		goto yy219
	default:
		goto yy14
	}
yy197:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'c':
		goto yy220
	default:
		goto yy14
	}
yy198:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy199
	}
yy199:
//line "lexer.go_":136
	{ addToken(KW_THIS); goto yyc_top }
//line "lexer.go":3393
yy200:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy221
	default:
		goto yy14
	}
yy201:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy202
	}
yy202:
//line "lexer.go_":137
	{ addToken(KW_TRUE); goto yyc_top }
//line "lexer.go":3543
yy203:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	case 'o':
		goto yy223
	default:
		goto yy204
	}
yy204:
//line "lexer.go_":116
	{ addToken(KW_TYPE); goto yyc_top }
//line "lexer.go":3682
yy205:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy206
	}
yy206:
//line "lexer.go_":135
	{ addToken(KW_VOID); goto yyc_top }
//line "lexer.go":3821
yy207:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy224
	default:
		goto yy14
	}
yy208:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'd':
		goto yy226
	default:
		goto yy14
	}
yy209:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy210
	}
yy210:
//line "lexer.go_":115
	{ addToken(KW_CONST); goto yyc_top }
//line "lexer.go":3982
yy211:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy228
	default:
		goto yy14
	}
yy212:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy213
	}
yy213:
//line "lexer.go_":138
	{ addToken(KW_FALSE); goto yyc_top }
//line "lexer.go":4132
yy214:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy230
	default:
		goto yy14
	}
yy215:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy216
	}
yy216:
//line "lexer.go_":112
	{ addToken(KW_LOCAL); goto yyc_top }
//line "lexer.go":4282
yy217:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'd':
		goto yy232
	default:
		goto yy14
	}
yy218:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'p':
		goto yy234
	default:
		goto yy14
	}
yy219:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'n':
		goto yy235
	default:
		goto yy14
	}
yy220:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 't':
		goto yy237
	default:
		goto yy14
	}
yy221:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy222
	}
yy222:
//line "lexer.go_":120
	{ addToken(KW_TRAIT); goto yyc_top }
//line "lexer.go":4465
yy223:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'f':
		goto yy239
	default:
		goto yy14
	}
yy224:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy225
	}
yy225:
//line "lexer.go_":125
	{ addToken(KW_WHILE); goto yyc_top }
//line "lexer.go":4615
yy226:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy227
	}
yy227:
//line "lexer.go_":132
	{ addToken(KW_YIELD); goto yyc_top }
//line "lexer.go":4754
yy228:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy229
	}
yy229:
//line "lexer.go_":109
	{ addToken(KW_EXPORT); goto yyc_top }
//line "lexer.go":4893
yy230:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy231
	}
yy231:
//line "lexer.go_":108
	{ addToken(KW_IMPORT); goto yyc_top }
//line "lexer.go":5032
yy232:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy233
	}
yy233:
//line "lexer.go_":118
	{ addToken(KW_METHOD); goto yyc_top }
//line "lexer.go":5171
yy234:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'a':
		goto yy241
	default:
		goto yy14
	}
yy235:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy236
	}
yy236:
//line "lexer.go_":131
	{ addToken(KW_RETURN); goto yyc_top }
//line "lexer.go":5321
yy237:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy238
	}
yy238:
//line "lexer.go_":121
	{ addToken(KW_STRUCT); goto yyc_top }
//line "lexer.go":5460
yy239:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy240
	}
yy240:
//line "lexer.go_":129
	{ addToken(KW_TYPEOF); goto yyc_top }
//line "lexer.go":5599
yy241:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'c':
		goto yy242
	default:
		goto yy14
	}
yy242:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy15
	case 'e':
		goto yy243
	default:
		goto yy14
	}
yy243:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy13
	default:
		goto yy244
	}
yy244:
//line "lexer.go_":107
	{ addToken(KW_NAMESPACE); goto yyc_top }
//line "lexer.go":5760
yyeof1_top:
//line "lexer.go_":102
	{ addToken(TK_EOF); return nil }
//line "lexer.go":5764
/* *********************************** */
yyc_comment:
	yych = data[offset]
	switch (yych) {
	case '#':
		goto yy250
	default:
		if (offset >= length - 1) {
			goto yyeof1_comment
		}
		goto yy247
	}
yy247:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '#':
		goto yy249
	default:
		if (offset >= length - 1) {
			goto yy249
		}
		goto yy247
	}
yy249:
	goto yyc_comment
yy250:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '(':
		goto yy252
	case ')':
		goto yy254
	default:
		goto yy251
	}
yy251:
	goto yyc_comment
yy252:
	offset += 1
//line "lexer.go_":208
	{ comment++; goto yyc_comment }
//line "lexer.go":5808
yy254:
	offset += 1
//line "lexer.go_":209
	{ comment--; if comment == 0 {
				if doc_comment {
					addToken(TK_DOCCOMMENT)
				} else {
					addToken(TK_COMMENT)
				}
				goto yyc_top
				} else { goto yyc_comment } }
//line "lexer.go":5820
yyeof1_comment:
//line "lexer.go_":217
	{ err() }
//line "lexer.go":5824
/* *********************************** */
yyc_str:
	yych = data[offset]
	switch (yych) {
	case '"':
		goto yy261
	case '\\':
		goto yy263
	case '{':
		goto yy265
	default:
		if (offset >= length - 1) {
			goto yyeof1_str
		}
		goto yy258
	}
yy258:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '"':
		fallthrough
	case '\\':
		fallthrough
	case '{':
		goto yy260
	default:
		if (offset >= length - 1) {
			goto yy260
		}
		goto yy258
	}
yy260:
//line "lexer.go_":226
	{ addToken(TK_RAWSTR); goto yyc_str }
//line "lexer.go":5860
yy261:
	offset += 1
//line "lexer.go_":220
	{ addToken(TK_QUOTE); goto yyc_top }
//line "lexer.go":5865
yy263:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy264
	default:
		if (offset >= length - 1) {
			goto yy264
		}
		goto yy267
	}
yy264:
//line "lexer.go_":228
	{ return err() }
//line "lexer.go":5881
yy265:
	offset += 1
	cond = yyctop
//line "lexer.go_":221
	{
				addToken(TK_LBRACKET)
				brace_stack = brace_stack.push()
				goto yyc_top
			}
//line "lexer.go":5891
yy267:
	offset += 1
//line "lexer.go_":219
	{ addToken(TK_CHAR); goto yyc_str }
//line "lexer.go":5896
yyeof1_str:
//line "lexer.go_":229
	{ return err() }
//line "lexer.go":5900
}
//line "lexer.go_":230


	return nil
}
const (
  TK_EOF TokenKind = iota
KW_AS
KW_CONST
KW_ELSE
KW_ENUM
KW_EXPORT
KW_FALSE
KW_FN
KW_FOR
KW_IF
KW_IMPORT
KW_IN
KW_IS
KW_ISO
KW_LOCAL
KW_METHOD
KW_NAMESPACE
KW_NONE
KW_RETURN
KW_STRUCT
KW_THIS
KW_TRAIT
KW_TRUE
KW_TYPE
KW_TYPEOF
KW_VAR
KW_VOID
KW_WHILE
KW_YIELD
TK_AMP
TK_AMPEQ
TK_ARROW
TK_AT
TK_CHAR
TK_COLON
TK_COMMA
TK_COMMENT
TK_DIV
TK_DIVEQ
TK_DOCCOMMENT
TK_DOT
TK_ELLIPSIS
TK_EQ
TK_EQEQ
TK_EXCLAM
TK_FATARROW
TK_GT
TK_ID
TK_LBRACE
TK_LBRACKET
TK_LPAREN
TK_LT
TK_MIN
TK_MINEQ
TK_MINMIN
TK_MOD
TK_MODEQ
TK_NOTEQ
TK_NUMBER
TK_PIPE
TK_PLUS
TK_PLUSEQ
TK_PLUSPLUS
TK_QUESTION
TK_QUESTIONDOT
TK_QUESTIONEQ
TK_QUOTE
TK_RAWSTR
TK_RBRACE
TK_RBRACKET
TK_RPAREN
TK_SEMICOLON
TK_STAR
TK_STAREQ
TK_WHITESPACE
TK__MAX
)
var tokstr = [...]string{
KW_AS: "KW_AS",
KW_CONST: "KW_CONST",
KW_ELSE: "KW_ELSE",
KW_ENUM: "KW_ENUM",
KW_EXPORT: "KW_EXPORT",
KW_FALSE: "KW_FALSE",
KW_FN: "KW_FN",
KW_FOR: "KW_FOR",
KW_IF: "KW_IF",
KW_IMPORT: "KW_IMPORT",
KW_IN: "KW_IN",
KW_IS: "KW_IS",
KW_ISO: "KW_ISO",
KW_LOCAL: "KW_LOCAL",
KW_METHOD: "KW_METHOD",
KW_NAMESPACE: "KW_NAMESPACE",
KW_NONE: "KW_NONE",
KW_RETURN: "KW_RETURN",
KW_STRUCT: "KW_STRUCT",
KW_THIS: "KW_THIS",
KW_TRAIT: "KW_TRAIT",
KW_TRUE: "KW_TRUE",
KW_TYPE: "KW_TYPE",
KW_TYPEOF: "KW_TYPEOF",
KW_VAR: "KW_VAR",
KW_VOID: "KW_VOID",
KW_WHILE: "KW_WHILE",
KW_YIELD: "KW_YIELD",
TK_AMP: "TK_AMP",
TK_AMPEQ: "TK_AMPEQ",
TK_ARROW: "TK_ARROW",
TK_AT: "TK_AT",
TK_CHAR: "TK_CHAR",
TK_COLON: "TK_COLON",
TK_COMMA: "TK_COMMA",
TK_COMMENT: "TK_COMMENT",
TK_DIV: "TK_DIV",
TK_DIVEQ: "TK_DIVEQ",
TK_DOCCOMMENT: "TK_DOCCOMMENT",
TK_DOT: "TK_DOT",
TK_ELLIPSIS: "TK_ELLIPSIS",
TK_EOF: "TK_EOF",
TK_EQ: "TK_EQ",
TK_EQEQ: "TK_EQEQ",
TK_EXCLAM: "TK_EXCLAM",
TK_FATARROW: "TK_FATARROW",
TK_GT: "TK_GT",
TK_ID: "TK_ID",
TK_LBRACE: "TK_LBRACE",
TK_LBRACKET: "TK_LBRACKET",
TK_LPAREN: "TK_LPAREN",
TK_LT: "TK_LT",
TK_MIN: "TK_MIN",
TK_MINEQ: "TK_MINEQ",
TK_MINMIN: "TK_MINMIN",
TK_MOD: "TK_MOD",
TK_MODEQ: "TK_MODEQ",
TK_NOTEQ: "TK_NOTEQ",
TK_NUMBER: "TK_NUMBER",
TK_PIPE: "TK_PIPE",
TK_PLUS: "TK_PLUS",
TK_PLUSEQ: "TK_PLUSEQ",
TK_PLUSPLUS: "TK_PLUSPLUS",
TK_QUESTION: "TK_QUESTION",
TK_QUESTIONDOT: "TK_QUESTIONDOT",
TK_QUESTIONEQ: "TK_QUESTIONEQ",
TK_QUOTE: "TK_QUOTE",
TK_RAWSTR: "TK_RAWSTR",
TK_RBRACE: "TK_RBRACE",
TK_RBRACKET: "TK_RBRACKET",
TK_RPAREN: "TK_RPAREN",
TK_SEMICOLON: "TK_SEMICOLON",
TK_STAR: "TK_STAR",
TK_STAREQ: "TK_STAREQ",
TK_WHITESPACE: "TK_WHITESPACE",
}
