// Code generated by re2c 2.0.3 on Tue Nov 10 14:51:02 2020, DO NOT EDIT.
//line "lexer.go_":1
package zoe

type LexerError struct {
	Filename string
	Message  string
	Line     int
	Column   int
	Offset   int
}

func (l LexerError) Error() string {
	return l.Message
}

// Lex
func (z *ZoeContext) Lex() error {
	//line "lexer.go":20
const (
	yyctop = iota
	yyccomment
	yycstr
)
//line "lexer.go_":17

	data, length := z.data, len(z.data)
	offset := 0
	start := 0
	line := 1
	col := 1
	cond := yyctop
	comment := 0 // recursive comments
	doc_comment := false

	var marker int

	var updateLines = func() {
		for i := start; i < offset; i++ {
			char := data[i]
			if char == '\n' {
				line++
				col = 1
			} else {
				col++
			}
		}
	}

	var err = func() error {
		offset--
		updateLines()
		return LexerError{Message: "invalid input '" + string(data[offset]) + "'", Line: line, Column: col, Offset: offset, Filename: z.Filename}
	}

	var addTokenBounds = func(kind TokenKind, offsetStart int, offsetEnd int) {
		n := &Token{}
		// n.Value = string(value)
		n.Context = z
		n.Start = start + offsetStart
		n.End = offset + offsetEnd
		n.Kind = kind
		n.Line = line
		n.Column = col
		updateLines()

		start = offset
		n.EndLine = line
		n.EndColumn = col

		is_meaningful := kind != TK_WHITESPACE && kind != TK_COMMENT

		// count lines and columns before adding

		if z.WsEnd == nil {
			z.WsStart = n
			z.WsEnd = n
		} else {
			z.WsEnd.WsNext = n
			z.WsEnd = n
		}

		if is_meaningful {
			if z.End == nil {
				z.Start = n
				z.End = n
			} else {
				z.End.Next = n
				z.End = n
			}
		}
	}

	var addToken = func(kind TokenKind) {
		addTokenBounds(kind, 0, 0)
	}

	
//line "lexer.go":100
{
	var yych byte
	yyaccept := 0
	switch (cond) {
	case yyctop:
		goto yyc_top
	case yyccomment:
		goto yyc_comment
	case yycstr:
		goto yyc_str
	}
/* *********************************** */
yyc_top:
	yych = data[offset]
	switch (yych) {
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case ' ':
		goto yy4
	case '!':
		goto yy7
	case '"':
		goto yy8
	case '#':
		goto yy10
	case '$':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'b':
		fallthrough
	case 'd':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'm':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'u':
		fallthrough
	case 'x':
		fallthrough
	case 'z':
		goto yy12
	case '%':
		goto yy15
	case '&':
		goto yy17
	case '\'':
		goto yy19
	case '(':
		goto yy20
	case ')':
		goto yy22
	case '*':
		goto yy24
	case '+':
		goto yy26
	case ',':
		goto yy28
	case '-':
		goto yy30
	case '.':
		goto yy32
	case '/':
		goto yy34
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy36
	case ':':
		goto yy39
	case ';':
		goto yy41
	case '<':
		goto yy43
	case '=':
		goto yy45
	case '>':
		goto yy47
	case '?':
		goto yy49
	case '@':
		goto yy51
	case '[':
		goto yy53
	case '\\':
		goto yy55
	case ']':
		goto yy56
	case 'a':
		goto yy58
	case 'c':
		goto yy59
	case 'e':
		goto yy60
	case 'f':
		goto yy61
	case 'i':
		goto yy62
	case 'l':
		goto yy63
	case 'n':
		goto yy64
	case 'r':
		goto yy65
	case 's':
		goto yy66
	case 't':
		goto yy67
	case 'v':
		goto yy68
	case 'w':
		goto yy69
	case 'y':
		goto yy70
	case '{':
		goto yy71
	case '|':
		goto yy73
	case '}':
		goto yy75
	default:
		if (offset >= length - 1) {
			goto yyeof1_top
		}
		goto yy2
	}
yy2:
	offset += 1
yy3:
//line "lexer.go_":104
	{ return err() }
//line "lexer.go":315
yy4:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case ' ':
		goto yy4
	default:
		goto yy6
	}
yy6:
//line "lexer.go_":106
	{ addToken(TK_WHITESPACE); goto yyc_top }
//line "lexer.go":332
yy7:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy77
	default:
		goto yy3
	}
yy8:
	offset += 1
	cond = yycstr
//line "lexer.go_":182
	{ addToken(TK_QUOTE); goto yyc_str }
//line "lexer.go":347
yy10:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		if (offset >= length - 1) {
			goto yy11
		}
		goto yy79
	case '(':
		goto yy81
	default:
		goto yy80
	}
yy11:
//line "lexer.go_":181
	{ addToken(TK_COMMENT); goto yyc_top }
//line "lexer.go":365
yy12:
	offset += 1
	yych = data[offset]
yy13:
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy14
	}
yy14:
//line "lexer.go_":135
	{ addToken(TK_ID); goto yyc_top }
//line "lexer.go":505
yy15:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy83
	default:
		goto yy16
	}
yy16:
//line "lexer.go_":167
	{ addToken(TK_MOD); goto yyc_top }
//line "lexer.go":518
yy17:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy85
	default:
		goto yy18
	}
yy18:
//line "lexer.go_":165
	{ addToken(TK_AMP); goto yyc_top }
//line "lexer.go":531
yy19:
	yyaccept = 0
	offset += 1
	marker = offset
	yych = data[offset]
	if (yych <= 0x00) {
		if (offset >= length - 1) {
			goto yy3
		}
		goto yy87
	}
	goto yy88
yy20:
	offset += 1
//line "lexer.go_":140
	{ addToken(TK_LPAREN); goto yyc_top }
//line "lexer.go":548
yy22:
	offset += 1
//line "lexer.go_":141
	{ addToken(TK_RPAREN); goto yyc_top }
//line "lexer.go":553
yy24:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy93
	default:
		goto yy25
	}
yy25:
//line "lexer.go_":163
	{ addToken(TK_STAR); goto yyc_top }
//line "lexer.go":566
yy26:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '+':
		goto yy95
	case '=':
		goto yy97
	default:
		goto yy27
	}
yy27:
//line "lexer.go_":157
	{ addToken(TK_PLUS); goto yyc_top }
//line "lexer.go":581
yy28:
	offset += 1
//line "lexer.go_":153
	{ addToken(TK_COMMA); goto yyc_top }
//line "lexer.go":586
yy30:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '-':
		goto yy99
	case '=':
		goto yy101
	case '>':
		goto yy103
	default:
		goto yy31
	}
yy31:
//line "lexer.go_":160
	{ addToken(TK_MIN); goto yyc_top }
//line "lexer.go":603
yy32:
	yyaccept = 1
	offset += 1
	marker = offset
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy105
	default:
		goto yy33
	}
yy33:
//line "lexer.go_":152
	{ addToken(TK_DOT); goto yyc_top }
//line "lexer.go":618
yy34:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy107
	default:
		goto yy35
	}
yy35:
//line "lexer.go_":149
	{ addToken(TK_DIV); goto yyc_top }
//line "lexer.go":631
yy36:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy36
	default:
		goto yy38
	}
yy38:
//line "lexer.go_":136
	{ addToken(TK_NUMBER); goto yyc_top }
//line "lexer.go":662
yy39:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case ':':
		goto yy109
	default:
		goto yy40
	}
yy40:
//line "lexer.go_":154
	{ addToken(TK_COLON); goto yyc_top }
//line "lexer.go":675
yy41:
	offset += 1
//line "lexer.go_":156
	{ addToken(TK_SEMICOLON); goto yyc_top }
//line "lexer.go":680
yy43:
	offset += 1
//line "lexer.go_":146
	{ addToken(TK_LT); goto yyc_top }
//line "lexer.go":685
yy45:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '=':
		goto yy111
	case '>':
		goto yy113
	default:
		goto yy46
	}
yy46:
//line "lexer.go_":169
	{ addToken(TK_EQ); goto yyc_top }
//line "lexer.go":700
yy47:
	offset += 1
//line "lexer.go_":147
	{ addToken(TK_GT); goto yyc_top }
//line "lexer.go":705
yy49:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy115
	case '=':
		goto yy117
	default:
		goto yy50
	}
yy50:
//line "lexer.go_":175
	{ addToken(TK_QUESTION); goto yyc_top }
//line "lexer.go":720
yy51:
	offset += 1
//line "lexer.go_":174
	{ addToken(TK_AT); goto yyc_top }
//line "lexer.go":725
yy53:
	offset += 1
//line "lexer.go_":142
	{ addToken(TK_LBRACE); goto yyc_top }
//line "lexer.go":730
yy55:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x07:
		fallthrough
	case 0x08:
		fallthrough
	case '\t':
		fallthrough
	case '\n':
		fallthrough
	case '\v':
		fallthrough
	case '\r':
		fallthrough
	case ' ':
		goto yy3
	case '\\':
		goto yy121
	default:
		if (offset >= length - 1) {
			goto yy3
		}
		goto yy119
	}
yy56:
	offset += 1
//line "lexer.go_":143
	{ addToken(TK_RBRACE); goto yyc_top }
//line "lexer.go":761
yy58:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 's':
		goto yy122
	default:
		goto yy13
	}
yy59:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'o':
		goto yy124
	default:
		goto yy13
	}
yy60:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'l':
		goto yy125
	case 'n':
		goto yy126
	case 'x':
		goto yy127
	default:
		goto yy13
	}
yy61:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'n':
		goto yy128
	case 'o':
		goto yy130
	default:
		goto yy13
	}
yy62:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'f':
		goto yy131
	case 'm':
		goto yy133
	case 'n':
		goto yy134
	case 's':
		goto yy136
	default:
		goto yy13
	}
yy63:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'o':
		goto yy138
	default:
		goto yy13
	}
yy64:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'a':
		goto yy139
	default:
		goto yy13
	}
yy65:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy140
	default:
		goto yy13
	}
yy66:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy141
	default:
		goto yy13
	}
yy67:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy142
	case 'r':
		goto yy143
	case 'y':
		goto yy144
	default:
		goto yy13
	}
yy68:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'a':
		goto yy145
	default:
		goto yy13
	}
yy69:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'h':
		goto yy146
	default:
		goto yy13
	}
yy70:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'i':
		goto yy147
	default:
		goto yy13
	}
yy71:
	offset += 1
//line "lexer.go_":144
	{ addToken(TK_LBRACKET); goto yyc_top }
//line "lexer.go":925
yy73:
	offset += 1
//line "lexer.go_":148
	{ addToken(TK_PIPE); goto yyc_top }
//line "lexer.go":930
yy75:
	offset += 1
//line "lexer.go_":145
	{ addToken(TK_RBRACKET); goto yyc_top }
//line "lexer.go":935
yy77:
	offset += 1
//line "lexer.go_":173
	{ addToken(TK_NOTEQ); goto yyc_top }
//line "lexer.go":940
yy79:
	offset += 1
	yych = data[offset]
yy80:
	switch (yych) {
	case '\n':
		goto yy11
	default:
		if (offset >= length - 1) {
			goto yy11
		}
		goto yy79
	}
yy81:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy82
	case '?':
		goto yy148
	default:
		if (offset >= length - 1) {
			goto yy82
		}
		goto yy79
	}
yy82:
//line "lexer.go_":179
	{ doc_comment = false; comment++; goto yyc_comment }
//line "lexer.go":971
yy83:
	offset += 1
//line "lexer.go_":168
	{ addToken(TK_MODEQ); goto yyc_top }
//line "lexer.go":976
yy85:
	offset += 1
//line "lexer.go_":166
	{ addToken(TK_AMPEQ); goto yyc_top }
//line "lexer.go":981
yy87:
	offset += 1
	yych = data[offset]
yy88:
	switch (yych) {
	case '\'':
		goto yy89
	case '\\':
		goto yy91
	default:
		if (offset >= length - 1) {
			goto yy106
		}
		goto yy87
	}
yy89:
	offset += 1
yy90:
//line "lexer.go_":183
	{ addToken(TK_RAWSTR); goto yyc_top }
//line "lexer.go":1002
yy91:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\'':
		goto yy150
	case '\\':
		goto yy91
	default:
		if (offset >= length - 1) {
			goto yy106
		}
		goto yy87
	}
yy93:
	offset += 1
//line "lexer.go_":164
	{ addToken(TK_STAREQ); goto yyc_top }
//line "lexer.go":1021
yy95:
	offset += 1
//line "lexer.go_":159
	{ addToken(TK_PLUSPLUS); goto yyc_top }
//line "lexer.go":1026
yy97:
	offset += 1
//line "lexer.go_":158
	{ addToken(TK_PLUSEQ); goto yyc_top }
//line "lexer.go":1031
yy99:
	offset += 1
//line "lexer.go_":162
	{ addToken(TK_MINMIN); goto yyc_top }
//line "lexer.go":1036
yy101:
	offset += 1
//line "lexer.go_":161
	{ addToken(TK_MINEQ); goto yyc_top }
//line "lexer.go":1041
yy103:
	offset += 1
//line "lexer.go_":172
	{ addToken(TK_ARROW); goto yyc_top }
//line "lexer.go":1046
yy105:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '.':
		goto yy151
	default:
		goto yy106
	}
yy106:
	offset = marker
	switch (yyaccept) {
	case 0:
		goto yy3
	case 1:
		goto yy33
	default:
		goto yy90
	}
yy107:
	offset += 1
//line "lexer.go_":150
	{ addToken(TK_DIVEQ); goto yyc_top }
//line "lexer.go":1070
yy109:
	offset += 1
//line "lexer.go_":155
	{ addToken(TK_COLCOL); goto yyc_top }
//line "lexer.go":1075
yy111:
	offset += 1
//line "lexer.go_":170
	{ addToken(TK_EQEQ); goto yyc_top }
//line "lexer.go":1080
yy113:
	offset += 1
//line "lexer.go_":171
	{ addToken(TK_FATARROW); goto yyc_top }
//line "lexer.go":1085
yy115:
	offset += 1
//line "lexer.go_":176
	{ addToken(TK_QUESTIONDOT); goto yyc_top }
//line "lexer.go":1090
yy117:
	offset += 1
//line "lexer.go_":177
	{ addToken(TK_QUESTIONEQ); goto yyc_top }
//line "lexer.go":1095
yy119:
	offset += 1
yy120:
//line "lexer.go_":138
	{ addToken(TK_CHAR); goto yyc_top }
//line "lexer.go":1101
yy121:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'f':
		fallthrough
	case 'n':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'v':
		fallthrough
	case 'x':
		goto yy119
	default:
		goto yy120
	}
yy122:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy123
	}
yy123:
//line "lexer.go_":111
	{ addToken(KW_AS); goto yyc_top }
//line "lexer.go":1265
yy124:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'n':
		goto yy153
	default:
		goto yy13
	}
yy125:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 's':
		goto yy154
	default:
		goto yy13
	}
yy126:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'u':
		goto yy155
	default:
		goto yy13
	}
yy127:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'p':
		goto yy156
	default:
		goto yy13
	}
yy128:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy129
	}
yy129:
//line "lexer.go_":119
	{ addToken(KW_FN); goto yyc_top }
//line "lexer.go":1448
yy130:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'r':
		goto yy157
	default:
		goto yy13
	}
yy131:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy132
	}
yy132:
//line "lexer.go_":127
	{ addToken(KW_IF); goto yyc_top }
//line "lexer.go":1598
yy133:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'p':
		goto yy159
	default:
		goto yy13
	}
yy134:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy135
	}
yy135:
//line "lexer.go_":125
	{ addToken(KW_IN); goto yyc_top }
//line "lexer.go":1748
yy136:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy137
	}
yy137:
//line "lexer.go_":131
	{ addToken(KW_IS); goto yyc_top }
//line "lexer.go":1887
yy138:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'c':
		goto yy160
	default:
		goto yy13
	}
yy139:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'm':
		goto yy161
	default:
		goto yy13
	}
yy140:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy162
	default:
		goto yy13
	}
yy141:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'r':
		goto yy163
	default:
		goto yy13
	}
yy142:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'm':
		goto yy164
	default:
		goto yy13
	}
yy143:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'a':
		goto yy165
	default:
		goto yy13
	}
yy144:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'p':
		goto yy166
	default:
		goto yy13
	}
yy145:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'r':
		goto yy167
	default:
		goto yy13
	}
yy146:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'i':
		goto yy169
	default:
		goto yy13
	}
yy147:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy170
	default:
		goto yy13
	}
yy148:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy149
	default:
		if (offset >= length - 1) {
			goto yy149
		}
		goto yy79
	}
yy149:
//line "lexer.go_":180
	{ doc_comment = true; comment++; goto yyc_comment }
//line "lexer.go":2013
yy150:
	yyaccept = 2
	offset += 1
	marker = offset
	yych = data[offset]
	switch (yych) {
	case '\'':
		goto yy89
	case '\\':
		goto yy91
	default:
		if (offset >= length - 1) {
			goto yy90
		}
		goto yy87
	}
yy151:
	offset += 1
//line "lexer.go_":151
	{ addToken(TK_ELLIPSIS); goto yyc_top }
//line "lexer.go":2034
yy153:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 's':
		goto yy171
	default:
		goto yy13
	}
yy154:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy172
	default:
		goto yy13
	}
yy155:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'm':
		goto yy174
	default:
		goto yy13
	}
yy156:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'o':
		goto yy176
	default:
		goto yy13
	}
yy157:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy158
	}
yy158:
//line "lexer.go_":124
	{ addToken(KW_FOR); goto yyc_top }
//line "lexer.go":2217
yy159:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'o':
		goto yy177
	default:
		goto yy13
	}
yy160:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'a':
		goto yy178
	default:
		goto yy13
	}
yy161:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy179
	default:
		goto yy13
	}
yy162:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'u':
		goto yy180
	default:
		goto yy13
	}
yy163:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'u':
		goto yy181
	default:
		goto yy13
	}
yy164:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'p':
		goto yy182
	default:
		goto yy13
	}
yy165:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'i':
		goto yy183
	default:
		goto yy13
	}
yy166:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy184
	default:
		goto yy13
	}
yy167:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy168
	}
yy168:
//line "lexer.go_":115
	{ addToken(KW_VAR); goto yyc_top }
//line "lexer.go":2444
yy169:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'l':
		goto yy186
	default:
		goto yy13
	}
yy170:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'l':
		goto yy187
	default:
		goto yy13
	}
yy171:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy188
	default:
		goto yy13
	}
yy172:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy173
	}
yy173:
//line "lexer.go_":128
	{ addToken(KW_ELSE); goto yyc_top }
//line "lexer.go":2616
yy174:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy175
	}
yy175:
//line "lexer.go_":120
	{ addToken(KW_ENUM); goto yyc_top }
//line "lexer.go":2755
yy176:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'r':
		goto yy190
	default:
		goto yy13
	}
yy177:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'r':
		goto yy191
	default:
		goto yy13
	}
yy178:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'l':
		goto yy192
	default:
		goto yy13
	}
yy179:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 's':
		goto yy194
	default:
		goto yy13
	}
yy180:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'r':
		goto yy195
	default:
		goto yy13
	}
yy181:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'c':
		goto yy196
	default:
		goto yy13
	}
yy182:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'l':
		goto yy197
	default:
		goto yy13
	}
yy183:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy198
	default:
		goto yy13
	}
yy184:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	case 'o':
		goto yy200
	default:
		goto yy185
	}
yy185:
//line "lexer.go_":118
	{ addToken(KW_TYPE); goto yyc_top }
//line "lexer.go":2982
yy186:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy201
	default:
		goto yy13
	}
yy187:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'd':
		goto yy203
	default:
		goto yy13
	}
yy188:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy189
	}
yy189:
//line "lexer.go_":116
	{ addToken(KW_CONST); goto yyc_top }
//line "lexer.go":3143
yy190:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy205
	default:
		goto yy13
	}
yy191:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy207
	default:
		goto yy13
	}
yy192:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy193
	}
yy193:
//line "lexer.go_":113
	{ addToken(KW_LOCAL); goto yyc_top }
//line "lexer.go":3304
yy194:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'p':
		goto yy209
	default:
		goto yy13
	}
yy195:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'n':
		goto yy210
	default:
		goto yy13
	}
yy196:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy212
	default:
		goto yy13
	}
yy197:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'a':
		goto yy214
	default:
		goto yy13
	}
yy198:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy199
	}
yy199:
//line "lexer.go_":121
	{ addToken(KW_TRAIT); goto yyc_top }
//line "lexer.go":3487
yy200:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'f':
		goto yy215
	default:
		goto yy13
	}
yy201:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy202
	}
yy202:
//line "lexer.go_":126
	{ addToken(KW_WHILE); goto yyc_top }
//line "lexer.go":3637
yy203:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy204
	}
yy204:
//line "lexer.go_":133
	{ addToken(KW_YIELD); goto yyc_top }
//line "lexer.go":3776
yy205:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy206
	}
yy206:
//line "lexer.go_":110
	{ addToken(KW_EXPORT); goto yyc_top }
//line "lexer.go":3915
yy207:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy208
	}
yy208:
//line "lexer.go_":109
	{ addToken(KW_IMPORT); goto yyc_top }
//line "lexer.go":4054
yy209:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'a':
		goto yy217
	default:
		goto yy13
	}
yy210:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy211
	}
yy211:
//line "lexer.go_":132
	{ addToken(KW_RETURN); goto yyc_top }
//line "lexer.go":4204
yy212:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy213
	}
yy213:
//line "lexer.go_":122
	{ addToken(KW_STRUCT); goto yyc_top }
//line "lexer.go":4343
yy214:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 't':
		goto yy218
	default:
		goto yy13
	}
yy215:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy216
	}
yy216:
//line "lexer.go_":130
	{ addToken(KW_TYPEOF); goto yyc_top }
//line "lexer.go":4493
yy217:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'c':
		goto yy219
	default:
		goto yy13
	}
yy218:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy220
	default:
		goto yy13
	}
yy219:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case 0x00:
		goto yy14
	case 'e':
		goto yy222
	default:
		goto yy13
	}
yy220:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy221
	}
yy221:
//line "lexer.go_":117
	{ addToken(KW_TEMPLATE); goto yyc_top }
//line "lexer.go":4665
yy222:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '$':
		fallthrough
	case '0':
		fallthrough
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		fallthrough
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'f':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'm':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 'r':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy12
	default:
		goto yy223
	}
yy223:
//line "lexer.go_":108
	{ addToken(KW_NAMESPACE); goto yyc_top }
//line "lexer.go":4804
yyeof1_top:
//line "lexer.go_":103
	{ return nil }
//line "lexer.go":4808
/* *********************************** */
yyc_comment:
	yych = data[offset]
	switch (yych) {
	case '#':
		goto yy229
	default:
		if (offset >= length - 1) {
			goto yyeof1_comment
		}
		goto yy226
	}
yy226:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '#':
		goto yy228
	default:
		if (offset >= length - 1) {
			goto yy228
		}
		goto yy226
	}
yy228:
	goto yyc_comment
yy229:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '(':
		goto yy231
	case ')':
		goto yy233
	default:
		goto yy230
	}
yy230:
	goto yyc_comment
yy231:
	offset += 1
//line "lexer.go_":187
	{ comment++; goto yyc_comment }
//line "lexer.go":4852
yy233:
	offset += 1
//line "lexer.go_":188
	{ comment--; if comment == 0 {
				if doc_comment {
					addToken(TK_DOCCOMMENT)
				} else {
					addToken(TK_COMMENT)
				}
				goto yyc_top
				} else { goto yyc_comment } }
//line "lexer.go":4864
yyeof1_comment:
//line "lexer.go_":196
	{ err() }
//line "lexer.go":4868
/* *********************************** */
yyc_str:
	yych = data[offset]
	switch (yych) {
	case '"':
		goto yy240
	case '\\':
		goto yy242
	case '{':
		goto yy244
	default:
		if (offset >= length - 1) {
			goto yyeof1_str
		}
		goto yy237
	}
yy237:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '"':
		fallthrough
	case '\\':
		fallthrough
	case '{':
		goto yy239
	default:
		if (offset >= length - 1) {
			goto yy239
		}
		goto yy237
	}
yy239:
//line "lexer.go_":201
	{ addToken(TK_RAWSTR); goto yyc_str }
//line "lexer.go":4904
yy240:
	offset += 1
//line "lexer.go_":199
	{ addToken(TK_QUOTE); goto yyc_top }
//line "lexer.go":4909
yy242:
	offset += 1
	yych = data[offset]
	switch (yych) {
	case '\n':
		goto yy243
	default:
		if (offset >= length - 1) {
			goto yy243
		}
		goto yy246
	}
yy243:
//line "lexer.go_":203
	{ return err() }
//line "lexer.go":4925
yy244:
	offset += 1
	cond = yyctop
//line "lexer.go_":200
	{ addToken(TK_LBRACKET); goto yyc_top }
//line "lexer.go":4931
yy246:
	offset += 1
//line "lexer.go_":198
	{ addToken(TK_CHAR); goto yyc_str }
//line "lexer.go":4936
yyeof1_str:
//line "lexer.go_":204
	{ return err() }
//line "lexer.go":4940
}
//line "lexer.go_":205


	return nil
}
const (
  TK_EOF TokenKind = iota
KW_AS
KW_CONST
KW_ELSE
KW_ENUM
KW_EXPORT
KW_FN
KW_FOR
KW_IF
KW_IMPORT
KW_IN
KW_IS
KW_LOCAL
KW_NAMESPACE
KW_RETURN
KW_STRUCT
KW_TEMPLATE
KW_TRAIT
KW_TYPE
KW_TYPEOF
KW_VAR
KW_WHILE
KW_YIELD
TK_AMP
TK_AMPEQ
TK_ARROW
TK_AT
TK_CHAR
TK_COLCOL
TK_COLON
TK_COMMA
TK_COMMENT
TK_DIV
TK_DIVEQ
TK_DOCCOMMENT
TK_DOT
TK_ELLIPSIS
TK_EQ
TK_EQEQ
TK_FATARROW
TK_GT
TK_ID
TK_LBRACE
TK_LBRACKET
TK_LPAREN
TK_LT
TK_MIN
TK_MINEQ
TK_MINMIN
TK_MOD
TK_MODEQ
TK_NOTEQ
TK_NUMBER
TK_PIPE
TK_PLUS
TK_PLUSEQ
TK_PLUSPLUS
TK_QUESTION
TK_QUESTIONDOT
TK_QUESTIONEQ
TK_QUOTE
TK_RAWSTR
TK_RBRACE
TK_RBRACKET
TK_RPAREN
TK_SEMICOLON
TK_STAR
TK_STAREQ
TK_WHITESPACE
TK__MAX
)
var tokstr = [...]string{
KW_AS: "KW_AS",
KW_CONST: "KW_CONST",
KW_ELSE: "KW_ELSE",
KW_ENUM: "KW_ENUM",
KW_EXPORT: "KW_EXPORT",
KW_FN: "KW_FN",
KW_FOR: "KW_FOR",
KW_IF: "KW_IF",
KW_IMPORT: "KW_IMPORT",
KW_IN: "KW_IN",
KW_IS: "KW_IS",
KW_LOCAL: "KW_LOCAL",
KW_NAMESPACE: "KW_NAMESPACE",
KW_RETURN: "KW_RETURN",
KW_STRUCT: "KW_STRUCT",
KW_TEMPLATE: "KW_TEMPLATE",
KW_TRAIT: "KW_TRAIT",
KW_TYPE: "KW_TYPE",
KW_TYPEOF: "KW_TYPEOF",
KW_VAR: "KW_VAR",
KW_WHILE: "KW_WHILE",
KW_YIELD: "KW_YIELD",
TK_AMP: "TK_AMP",
TK_AMPEQ: "TK_AMPEQ",
TK_ARROW: "TK_ARROW",
TK_AT: "TK_AT",
TK_CHAR: "TK_CHAR",
TK_COLCOL: "TK_COLCOL",
TK_COLON: "TK_COLON",
TK_COMMA: "TK_COMMA",
TK_COMMENT: "TK_COMMENT",
TK_DIV: "TK_DIV",
TK_DIVEQ: "TK_DIVEQ",
TK_DOCCOMMENT: "TK_DOCCOMMENT",
TK_DOT: "TK_DOT",
TK_ELLIPSIS: "TK_ELLIPSIS",
TK_EQ: "TK_EQ",
TK_EQEQ: "TK_EQEQ",
TK_FATARROW: "TK_FATARROW",
TK_GT: "TK_GT",
TK_ID: "TK_ID",
TK_LBRACE: "TK_LBRACE",
TK_LBRACKET: "TK_LBRACKET",
TK_LPAREN: "TK_LPAREN",
TK_LT: "TK_LT",
TK_MIN: "TK_MIN",
TK_MINEQ: "TK_MINEQ",
TK_MINMIN: "TK_MINMIN",
TK_MOD: "TK_MOD",
TK_MODEQ: "TK_MODEQ",
TK_NOTEQ: "TK_NOTEQ",
TK_NUMBER: "TK_NUMBER",
TK_PIPE: "TK_PIPE",
TK_PLUS: "TK_PLUS",
TK_PLUSEQ: "TK_PLUSEQ",
TK_PLUSPLUS: "TK_PLUSPLUS",
TK_QUESTION: "TK_QUESTION",
TK_QUESTIONDOT: "TK_QUESTIONDOT",
TK_QUESTIONEQ: "TK_QUESTIONEQ",
TK_QUOTE: "TK_QUOTE",
TK_RAWSTR: "TK_RAWSTR",
TK_RBRACE: "TK_RBRACE",
TK_RBRACKET: "TK_RBRACKET",
TK_RPAREN: "TK_RPAREN",
TK_SEMICOLON: "TK_SEMICOLON",
TK_STAR: "TK_STAR",
TK_STAREQ: "TK_STAREQ",
TK_WHITESPACE: "TK_WHITESPACE",
}
